nelmio_api_doc:
  documentation:
    info:
      title: Digitale Schiene Deutschland
      description: Railway management software for Deutsche Bahn AG
      version: 0.1.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {jwt}'
        name: Authorization
        in: header
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
