twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  paths:
    "%kernel.project_dir%/templates": FOSRest
  form_themes: ['bundles/Forms/form_view.html.twig']