#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
  type: rest  # Required for ``RestYamlLoader`` to process imported routes
  prefix: /api
  resource: App\Controller\RestAPI\TrackObjectTypesController

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }