app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

fos_user_security_login:
  controller: fos_user.security.controller:loginAction
  path: /users/login/form

fos_user_security_check:
  controller: fos_user.security.controller:checkAction
  path: /users/login/form/check

fos_user_security_logout:
  controller: fos_user.security.controller:logoutAction
  path: /users/logout

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /admin/add-new-user

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile